
ALTER TABLE student 
ADD COLUMN dob DATE,
ADD COLUMN photo VARCHAR,
ADD COLUMN gender VARCHAR,
ADD COLUMN class VARCHAR,
ADD COLUMN fatherName VARCHAR,
ADD COLUMN motherName VARCHAR,
ADD COLUMN fatherProfession VARCHAR,
ADD COLUMN motherProfession VARCHAR,
ADD COLUMN address VARCHAR,
ADD COLUMN city VARCHAR,
ADD COLUMN state VARCHAR,
ADD COLUMN pinCode VARCHAR;



ALTER TABLE school 
ADD COLUMN logo VARCHAR;
	